{ config, pkgs, lib, nixpkgs-master, ... }:

{
    home = {
      shellAliases = {
        nixconfig = "kate /home/jankoh/.dotfiles";
        nixrebuild = ''cd /home/jankoh/.dotfiles && sudo nixos-rebuild switch --flake . --impure'';
        labymod = "appimage-run \"/home/jankoh/Appimages/LabyMod Launcher-latest.AppImage\"";
        netflix = "xdg-open https://www.netflix.com";
        nixsearch = "xdg-open https://search.nixos.org/packages";
        youtube = "xdg-open https://www.youtube.com/";
        disney = "xdg-open https://www.disneyplus.com/en-gb/select-profile";
        cleanold = "sudo nix-collect-garbage -d";
        switchgen = "sudo /run/current-system/bin/switch-to-configuration boot";
      };
    };

    home.packages = with pkgs; [
      flatpak
      neovim
      fastfetch
      libreoffice-still
      vscode-fhs
      discord
      dotnet-sdk_9
      gparted
      podman
      git
      openscad
      superTuxKart
      gimp
      qbittorrent
      github-desktop
      gtkhash
      heroic
      kdenlive
      geogebra
      onlyoffice-desktopeditors
      wine
      musescore
      orca-slicer
      htop
      vlc
      chromium
      gnome-keyring
      jdk23
      ];

    nixpkgs.config.allowUnfree = true;

    programs.bash = {
      enable = true;
      initExtra = "fastfetch";
    };

    #========================KDE_Settings================================
    programs.plasma = {
      enable = true;

      #overrideConfig =true;

      shortcuts = {
        "ActivityManager"."switch-to-activity-1f3c8de7-295d-4dc1-a04a-ceb99a4ef3a1" = [ ];
        "KDE Keyboard Layout Switcher"."Switch to Last-Used Keyboard Layout" = "Meta+Alt+L";
        "KDE Keyboard Layout Switcher"."Switch to Next Keyboard Layout" = "Meta+Alt+K";
        "kaccess"."Toggle Screen Reader On and Off" = "Meta+Alt+S";
        "kcm_touchpad"."Disable Touchpad" = "Touchpad Off";
        "kcm_touchpad"."Enable Touchpad" = "Touchpad On";
        "kcm_touchpad"."Toggle Touchpad" = ["Touchpad Toggle" "Meta+Ctrl+Zenkaku Hankaku,Touchpad Toggle" "Meta+Ctrl+Zenkaku Hankaku,Touchpad umschalten"];
        "kmix"."decrease_microphone_volume" = "Microphone Volume Down";
        "kmix"."decrease_volume" = "Volume Down";
        "kmix"."decrease_volume_small" = "Shift+Volume Down";
        "kmix"."increase_microphone_volume" = "Microphone Volume Up";
        "kmix"."increase_volume" = "Volume Up";
        "kmix"."increase_volume_small" = "Shift+Volume Up";
        "kmix"."mic_mute" = ["Microphone Mute" "Meta+Volume Mute,Microphone Mute" "Meta+Volume Mute,Mikrofon stummschalten"];
        "kmix"."mute" = "Volume Mute";
        "ksmserver"."Halt Without Confirmation" = "none,,Ohne Rückfrage herunterfahren";
        "ksmserver"."Lock Session" = ["Meta+L" "Screensaver,Meta+L" "Screensaver,Sitzung sperren"];
        "ksmserver"."Log Out" = "Ctrl+Alt+Del";
        "ksmserver"."Log Out Without Confirmation" = "none,,Ohne Rückfrage abmelden";
        "ksmserver"."LogOut" = "none,,Abmelden";
        "ksmserver"."Reboot" = "none,,Neu starten";
        "ksmserver"."Reboot Without Confirmation" = "none,,Ohne Rückfrage neu starten";
        "ksmserver"."Shut Down" = "none,,Herunterfahren";
        "kwin"."Activate Window Demanding Attention" = "Meta+Ctrl+A,Meta+Ctrl+A,Fenster aktivieren\\, das Aufmerksamkeit erfordert";
        "kwin"."Cycle Overview" = [ ];
        "kwin"."Cycle Overview Opposite" = [ ];
        "kwin"."Decrease Opacity" = "none,,Die Deckkraft des aktiven Fensters um 5 % verringern";
        "kwin"."Edit Tiles" = "Meta+T";
        "kwin"."Expose" = "Ctrl+F9";
        "kwin"."ExposeAll" = ["Ctrl+F10" "Launch (C),Ctrl+F10" "Launch (C),Fenster aller Arbeitsflächen anzeigen"];
        "kwin"."ExposeClass" = "Ctrl+F7";
        "kwin"."ExposeClassCurrentDesktop" = [ ];

        "kwin"."Grid View" = "Meta+N";

        "kwin"."Increase Opacity" = "none,,Die Deckkraft des aktiven Fensters um 5 % erhöhen";
        "kwin"."Kill Window" = "Meta+Ctrl+Esc";
        "kwin"."Move Tablet to Next Output" = [ ];
        "kwin"."MoveMouseToCenter" = "Meta+F6";
        "kwin"."MoveMouseToFocus" = "Meta+F5";
        "kwin"."MoveZoomDown" = [ ];
        "kwin"."MoveZoomLeft" = [ ];
        "kwin"."MoveZoomRight" = [ ];
        "kwin"."MoveZoomUp" = [ ];
        "kwin"."Overview" = "Meta+W";
        "kwin"."Setup Window Shortcut" = "none,,Kurzbefehl für Fenster einrichten";
        "kwin"."Show Desktop" = "Meta+D";
        "kwin"."Suspend Compositing" = "Alt+Shift+F12";
        "kwin"."Switch One Desktop Down" = "Meta+Ctrl+Down";
        "kwin"."Switch One Desktop Up" = "Meta+Ctrl+Up";
        "kwin"."Switch One Desktop to the Left" = "Meta+Ctrl+Left";
        "kwin"."Switch One Desktop to the Right" = "Meta+Ctrl+Right";
        "kwin"."Switch Window Down" = "Meta+Alt+Down";
        "kwin"."Switch Window Left" = "Meta+Alt+Left";
        "kwin"."Switch Window Right" = "Meta+Alt+Right";
        "kwin"."Switch Window Up" = "Meta+Alt+Up";
        "kwin"."Switch to Desktop 1" = "Ctrl+F1";
        "kwin"."Switch to Desktop 10" = "none,,Auf Arbeitsfläche 10 umschalten";
        "kwin"."Switch to Desktop 11" = "none,,Auf Arbeitsfläche 11 umschalten";
        "kwin"."Switch to Desktop 12" = "none,,Auf Arbeitsfläche 12 umschalten";
        "kwin"."Switch to Desktop 13" = "none,,Auf Arbeitsfläche 13 umschalten";
        "kwin"."Switch to Desktop 14" = "none,,Auf Arbeitsfläche 14 umschalten";
        "kwin"."Switch to Desktop 15" = "none,,Auf Arbeitsfläche 15 umschalten";
        "kwin"."Switch to Desktop 16" = "none,,Auf Arbeitsfläche 16 umschalten";
        "kwin"."Switch to Desktop 17" = "none,,Auf Arbeitsfläche 17 umschalten";
        "kwin"."Switch to Desktop 18" = "none,,Auf Arbeitsfläche 18 umschalten";
        "kwin"."Switch to Desktop 19" = "none,,Auf Arbeitsfläche 19 umschalten";
        "kwin"."Switch to Desktop 2" = "Ctrl+F2";
        "kwin"."Switch to Desktop 20" = "none,,Auf Arbeitsfläche 20 umschalten";
        "kwin"."Switch to Desktop 3" = "Ctrl+F3";
        "kwin"."Switch to Desktop 4" = "Ctrl+F4";
        "kwin"."Switch to Desktop 5" = "none,,Auf Arbeitsfläche 5 umschalten";
        "kwin"."Switch to Desktop 6" = "none,,Auf Arbeitsfläche 6 umschalten";
        "kwin"."Switch to Desktop 7" = "none,,Auf Arbeitsfläche 7 umschalten";
        "kwin"."Switch to Desktop 8" = "none,,Auf Arbeitsfläche 8 umschalten";
        "kwin"."Switch to Desktop 9" = "none,,Auf Arbeitsfläche 9 umschalten";
        "kwin"."Switch to Next Desktop" = "none,,Zur nächsten Arbeitsfläche umschalten";
        "kwin"."Switch to Next Screen" = "none,,Zum nächsten Bildschirm wechseln";
        "kwin"."Switch to Previous Desktop" = "none,,Zur vorherigen Arbeitsfläche umschalten";
        "kwin"."Switch to Previous Screen" = "none,,Zum vorherigen Bildschirm wechseln";
        "kwin"."Switch to Screen 0" = "none,,Zum Bildschirm 0 wechseln";
        "kwin"."Switch to Screen 1" = "none,,Zum Bildschirm 1 wechseln";
        "kwin"."Switch to Screen 2" = "none,,Zum Bildschirm 2 wechseln";
        "kwin"."Switch to Screen 3" = "none,,Zum Bildschirm 3 wechseln";
        "kwin"."Switch to Screen 4" = "none,,Zum Bildschirm 4 wechseln";
        "kwin"."Switch to Screen 5" = "none,,Zum Bildschirm 5 wechseln";
        "kwin"."Switch to Screen 6" = "none,,Zum Bildschirm 6 wechseln";
        "kwin"."Switch to Screen 7" = "none,,Zum Bildschirm 7 wechseln";
        "kwin"."Switch to Screen Above" = "none,,Zum Bildschirm oben wechseln";
        "kwin"."Switch to Screen Below" = "none,,Zum Bildschirm unten wechseln";
        "kwin"."Switch to Screen to the Left" = "none,,Zum Bildschirm links wechseln";
        "kwin"."Switch to Screen to the Right" = "none,,Zum Bildschirm rechts wechseln";
        "kwin"."Toggle Night Color" = [ ];
        "kwin"."Toggle Window Raise/Lower" = "none,,Fenster nach vorne/hinten";
        "kwin"."Walk Through Windows" = "Alt+Tab";
        "kwin"."Walk Through Windows (Reverse)" = "Alt+Shift+Tab";
        "kwin"."Walk Through Windows Alternative" = "none,,Alternatives Wechseln zwischen Fenstern";
        "kwin"."Walk Through Windows Alternative (Reverse)" = "none,,Alternatives Wechseln zwischen Fenstern (Gegenrichtung)";
        "kwin"."Walk Through Windows of Current Application" = "Alt+`";
        "kwin"."Walk Through Windows of Current Application (Reverse)" = "Alt+~";
        "kwin"."Walk Through Windows of Current Application Alternative" = "none,,Alternatives Wechseln zwischen Fenstern der aktuellen Anwendung";
        "kwin"."Walk Through Windows of Current Application Alternative (Reverse)" = "none,,Alternatives Wechseln zwischen Fenstern der aktuellen Anwendung (Gegenrichtung)";
        "kwin"."Window Above Other Windows" = "none,,Fenster im Vordergrund halten";
        "kwin"."Window Below Other Windows" = "none,,Fenster im Hintergrund halten";
        "kwin"."Window Close" = ["Alt+F4" "Meta+Q,Alt+F4,Fenster schließen"];
        "kwin"."Window Fullscreen" = "none,,Fenster auf Vollbildgröße";
        "kwin"."Window Grow Horizontal" = "none,,Fenster waagerecht maximieren";
        "kwin"."Window Grow Vertical" = "none,,Fenster senkrecht maximieren";
        "kwin"."Window Lower" = "none,,Fenster nach hinten";
        "kwin"."Window Maximize" = ["Meta+F" "Meta+PgUp,Meta+PgUp,Fenster maximieren"];
        "kwin"."Window Maximize Horizontal" = "none,,Fenster waagerecht maximieren";
        "kwin"."Window Maximize Vertical" = "none,,Fenster senkrecht maximieren";
        "kwin"."Window Minimize" = "Meta+PgDown";
        "kwin"."Window Move" = "none,,Fenster verschieben";
        "kwin"."Window Move Center" = "none,,Fenster zentrieren";
        "kwin"."Window No Border" = "none,,Titelleiste und Rahmen des Fensters ein-/ausschalten";
        "kwin"."Window On All Desktops" = "none,,Fenster auf allen Arbeitsflächen anzeigen";
        "kwin"."Window One Desktop Down" = "Meta+Ctrl+Shift+Down";
        "kwin"."Window One Desktop Up" = "Meta+Ctrl+Shift+Up";
        "kwin"."Window One Desktop to the Left" = "Meta+Ctrl+Shift+Left";
        "kwin"."Window One Desktop to the Right" = "Meta+Ctrl+Shift+Right";
        "kwin"."Window One Screen Down" = "none,,Fenster einen Bildschirm nach unten verschieben";
        "kwin"."Window One Screen Up" = "none,,Fenster einen Bildschirm nach oben verschieben";
        "kwin"."Window One Screen to the Left" = "none,,Fenster einen Bildschirm nach links verschieben";
        "kwin"."Window One Screen to the Right" = "none,,Fenster einen Bildschirm nach rechts verschieben";
        "kwin"."Window Operations Menu" = "Alt+F3";
        "kwin"."Window Pack Down" = "none,,Fenster nach unten verschieben";
        "kwin"."Window Pack Left" = "none,,Fenster nach links verschieben";
        "kwin"."Window Pack Right" = "none,,Fenster nach rechts verschieben";
        "kwin"."Window Pack Up" = "none,,Fenster nach oben verschieben";
        "kwin"."Window Quick Tile Bottom" = "Meta+Down";
        "kwin"."Window Quick Tile Bottom Left" = "none,,Fenster am linken unteren Bildschirmrand anordnen";
        "kwin"."Window Quick Tile Bottom Right" = "none,,Fenster am rechten unteren Bildschirmrand anordnen";
        "kwin"."Window Quick Tile Left" = "Meta+Left";
        "kwin"."Window Quick Tile Right" = "Meta+Right";
        "kwin"."Window Quick Tile Top" = "Meta+Up";
        "kwin"."Window Quick Tile Top Left" = "none,,Fenster am linken oberen Bildschirmrand anordnen";
        "kwin"."Window Quick Tile Top Right" = "none,,Fenster am rechten oberen Bildschirmrand anordnen";
        "kwin"."Window Raise" = "none,,Fenster nach vorne";
        "kwin"."Window Resize" = "none,,Fenstergröße ändern";
        "kwin"."Window Shade" = "none,,Fensterheber betätigen";
        "kwin"."Window Shrink Horizontal" = "none,,Fenster waagerecht verkleinern";
        "kwin"."Window Shrink Vertical" = "none,,Fenster senkrecht verkleinern";
        "kwin"."Window to Desktop 1" = "none,,Fenster auf Arbeitsfläche 1";
        "kwin"."Window to Desktop 10" = "none,,Fenster auf Arbeitsfläche 10";
        "kwin"."Window to Desktop 11" = "none,,Fenster auf Arbeitsfläche 11";
        "kwin"."Window to Desktop 12" = "none,,Fenster auf Arbeitsfläche 12";
        "kwin"."Window to Desktop 13" = "none,,Fenster auf Arbeitsfläche 13";
        "kwin"."Window to Desktop 14" = "none,,Fenster auf Arbeitsfläche 14";
        "kwin"."Window to Desktop 15" = "none,,Fenster auf Arbeitsfläche 15";
        "kwin"."Window to Desktop 16" = "none,,Fenster auf Arbeitsfläche 16";
        "kwin"."Window to Desktop 17" = "none,,Fenster auf Arbeitsfläche 17";
        "kwin"."Window to Desktop 18" = "none,,Fenster auf Arbeitsfläche 18";
        "kwin"."Window to Desktop 19" = "none,,Fenster auf Arbeitsfläche 19";
        "kwin"."Window to Desktop 2" = "none,,Fenster auf Arbeitsfläche 2";
        "kwin"."Window to Desktop 20" = "none,,Fenster auf Arbeitsfläche 20";
        "kwin"."Window to Desktop 3" = "none,,Fenster auf Arbeitsfläche 3";
        "kwin"."Window to Desktop 4" = "none,,Fenster auf Arbeitsfläche 4";
        "kwin"."Window to Desktop 5" = "none,,Fenster auf Arbeitsfläche 5";
        "kwin"."Window to Desktop 6" = "none,,Fenster auf Arbeitsfläche 6";
        "kwin"."Window to Desktop 7" = "none,,Fenster auf Arbeitsfläche 7";
        "kwin"."Window to Desktop 8" = "none,,Fenster auf Arbeitsfläche 8";
        "kwin"."Window to Desktop 9" = "none,,Fenster auf Arbeitsfläche 9";
        "kwin"."Window to Next Desktop" = "none,,Fenster auf nächste Arbeitsfläche verschieben";
        "kwin"."Window to Next Screen" = "Meta+Shift+Right";
        "kwin"."Window to Previous Desktop" = "none,,Fenster auf vorherige Arbeitsfläche verschieben";
        "kwin"."Window to Previous Screen" = "Meta+Shift+Left";
        "kwin"."Window to Screen 0" = "none,,Fenster auf Bildschirm 0 verschieben";
        "kwin"."Window to Screen 1" = "none,,Fenster auf Bildschirm 1 verschieben";
        "kwin"."Window to Screen 2" = "none,,Fenster auf Bildschirm 2 verschieben";
        "kwin"."Window to Screen 3" = "none,,Fenster auf Bildschirm 3 verschieben";
        "kwin"."Window to Screen 4" = "none,,Fenster auf Bildschirm 4 verschieben";
        "kwin"."Window to Screen 5" = "none,,Fenster auf Bildschirm 5 verschieben";
        "kwin"."Window to Screen 6" = "none,,Fenster auf Bildschirm 6 verschieben";
        "kwin"."Window to Screen 7" = "none,,Fenster auf Bildschirm 7 verschieben";
        "kwin"."view_actual_size" = "Meta+0";
        "kwin"."view_zoom_in" = ["Meta++" "Meta+=,Meta++" "Meta+=,Vergrößern"];
        "kwin"."view_zoom_out" = "Meta+-";
        "mediacontrol"."mediavolumedown" = "none,,Medienwiedergabe leiser";
        "mediacontrol"."mediavolumeup" = "none,,Medienwiedergabe lauter";
        "mediacontrol"."nextmedia" = "Media Next";
        "mediacontrol"."pausemedia" = "Media Pause";
        "mediacontrol"."playmedia" = "none,,Medienwiedergabe starten";
        "mediacontrol"."playpausemedia" = "Media Play";
        "mediacontrol"."previousmedia" = "Media Previous";
        "mediacontrol"."stopmedia" = "Media Stop";
        "org_kde_powerdevil"."Decrease Keyboard Brightness" = "Keyboard Brightness Down";
        "org_kde_powerdevil"."Decrease Screen Brightness" = "Monitor Brightness Down";
        "org_kde_powerdevil"."Decrease Screen Brightness Small" = "Shift+Monitor Brightness Down";
        "org_kde_powerdevil"."Hibernate" = "Hibernate";
        "org_kde_powerdevil"."Increase Keyboard Brightness" = "Keyboard Brightness Up";
        "org_kde_powerdevil"."Increase Screen Brightness" = "Monitor Brightness Up";
        "org_kde_powerdevil"."Increase Screen Brightness Small" = "Shift+Monitor Brightness Up";
        "org_kde_powerdevil"."PowerDown" = "Power Down";
        "org_kde_powerdevil"."PowerOff" = "Power Off";
        "org_kde_powerdevil"."Sleep" = "Sleep";
        "org_kde_powerdevil"."Toggle Keyboard Backlight" = "Keyboard Light On/Off";
        "org_kde_powerdevil"."Turn Off Screen" = [ ];
        "org_kde_powerdevil"."powerProfile" = ["Battery" "Meta+B,Battery" "Meta+B,Energieprofil wechseln"];
        "plasmashell"."activate application launcher" = ["Meta" "Alt+F1,Meta" "Alt+F1,Anwendungsstarter aktivieren"];
        "plasmashell"."activate task manager entry 1" = "Meta+1";
        "plasmashell"."activate task manager entry 10" = "none,Meta+0,Fensterleisteneintrag 10 aktivieren";
        "plasmashell"."activate task manager entry 2" = "Meta+2";
        "plasmashell"."activate task manager entry 3" = "Meta+3";
        "plasmashell"."activate task manager entry 4" = "Meta+4";
        "plasmashell"."activate task manager entry 5" = "Meta+5";
        "plasmashell"."activate task manager entry 6" = "Meta+6";
        "plasmashell"."activate task manager entry 7" = "Meta+7";
        "plasmashell"."activate task manager entry 8" = "Meta+8";
        "plasmashell"."activate task manager entry 9" = "Meta+9";
        "plasmashell"."clear-history" = "none,,Bisherigen Inhalt der Zwischenablage löschen";
        "plasmashell"."clipboard_action" = "Meta+Ctrl+X";
        "plasmashell"."cycle-panels" = "Meta+Alt+P";
        "plasmashell"."cycleNextAction" = "none,,Nächstes Element im Verlauf";
        "plasmashell"."cyclePrevAction" = "none,,Vorheriges Element im Verlauf";
        "plasmashell"."manage activities" = "none,Meta+Q,Aktivitätenwechsler anzeigen";
        "plasmashell"."next activity" = "Meta+A,none,Zwischen Aktivitäten wechseln";
        "plasmashell"."previous activity" = "Meta+Shift+A,none,Zwischen Aktivitäten wechseln (Gegenrichtung)";
        "plasmashell"."repeat_action" = "none,Meta+Ctrl+R,Aktionen der aktuellen Zwischenablage manuell aufrufen";
        "plasmashell"."show dashboard" = "Ctrl+F12";
        "plasmashell"."show-barcode" = "none,,Strichcode anzeigen …";
        "plasmashell"."show-on-mouse-pos" = "Meta+V";
        "plasmashell"."stop current activity" = "Meta+S";
        "plasmashell"."switch to next activity" = "none,,Zur nächsten Aktivität wechseln";
        "plasmashell"."switch to previous activity" = "none,,Zur vorherigen Aktivität wechseln";
        "plasmashell"."toggle do not disturb" = "none,,Nicht stören umschalten";
        "services/net.local.ghostty.desktop"."_launch" = "Ctrl+Alt+T";
        "services/org.kde.konsole.desktop"."_launch" = [ ];
      };
      configFile = {
        "baloofilerc"."General"."dbVersion" = 2;
        "baloofilerc"."General"."exclude filters" = "*~,*.part,*.o,*.la,*.lo,*.loT,*.moc,moc_*.cpp,qrc_*.cpp,ui_*.h,cmake_install.cmake,CMakeCache.txt,CTestTestfile.cmake,libtool,config.status,confdefs.h,autom4te,conftest,confstat,Makefile.am,*.gcode,.ninja_deps,.ninja_log,build.ninja,*.csproj,*.m4,*.rej,*.gmo,*.pc,*.omf,*.aux,*.tmp,*.po,*.vm*,*.nvram,*.rcore,*.swp,*.swap,lzo,litmain.sh,*.orig,.histfile.*,.xsession-errors*,*.map,*.so,*.a,*.db,*.qrc,*.ini,*.init,*.img,*.vdi,*.vbox*,vbox.log,*.qcow2,*.vmdk,*.vhd,*.vhdx,*.sql,*.sql.gz,*.ytdl,*.tfstate*,*.class,*.pyc,*.pyo,*.elc,*.qmlc,*.jsc,*.fastq,*.fq,*.gb,*.fasta,*.fna,*.gbff,*.faa,po,CVS,.svn,.git,_darcs,.bzr,.hg,CMakeFiles,CMakeTmp,CMakeTmpQmake,.moc,.obj,.pch,.uic,.npm,.yarn,.yarn-cache,__pycache__,node_modules,node_packages,nbproject,.terraform,.venv,venv,core-dumps,lost+found";
        "baloofilerc"."General"."exclude filters version" = 9;
        "dolphinrc"."General"."ViewPropsTimestamp" = "2024,12,28,12,57,29.471";
        "dolphinrc"."KFileDialog Settings"."Places Icons Auto-resize" = false;
        "dolphinrc"."KFileDialog Settings"."Places Icons Static Size" = 22;
        "kactivitymanagerdrc"."activities"."1f3c8de7-295d-4dc1-a04a-ceb99a4ef3a1" = "Standard";
        "kactivitymanagerdrc"."main"."currentActivity" = "1f3c8de7-295d-4dc1-a04a-ceb99a4ef3a1";
        "katerc"."General"."Days Meta Infos" = 30;
        "katerc"."General"."Save Meta Infos" = true;
        "katerc"."General"."Show Full Path in Title" = false;
        "katerc"."General"."Show Menu Bar" = true;
        "katerc"."General"."Show Status Bar" = true;
        "katerc"."General"."Show Tab Bar" = true;
        "katerc"."General"."Show Url Nav Bar" = true;
        "katerc"."KTextEditor Renderer"."Animate Bracket Matching" = false;
        "katerc"."KTextEditor Renderer"."Auto Color Theme Selection" = true;
        "katerc"."KTextEditor Renderer"."Color Theme" = "Breeze Dark";
        "katerc"."KTextEditor Renderer"."Line Height Multiplier" = 1;
        "katerc"."KTextEditor Renderer"."Show Indentation Lines" = false;
        "katerc"."KTextEditor Renderer"."Show Whole Bracket Expression" = false;
        "katerc"."KTextEditor Renderer"."Text Font" = "Hack,10,-1,7,400,0,0,0,0,0,0,0,0,0,0,1";
        "katerc"."KTextEditor Renderer"."Text Font Features" = "";
        "katerc"."KTextEditor Renderer"."Word Wrap Marker" = false;
        "katerc"."filetree"."editShade" = "31,81,106";
        "katerc"."filetree"."listMode" = false;
        "katerc"."filetree"."middleClickToClose" = false;
        "katerc"."filetree"."shadingEnabled" = true;
        "katerc"."filetree"."showCloseButton" = false;
        "katerc"."filetree"."showFullPathOnRoots" = false;
        "katerc"."filetree"."showToolbar" = true;
        "katerc"."filetree"."sortRole" = 0;
        "katerc"."filetree"."viewShade" = "81,49,95";
        "kcminputrc"."Libinput/1452/627/bcm5974"."DisableWhileTyping" = false;
        "kcminputrc"."Libinput/1452/627/bcm5974"."PointerAcceleration" = 0.400;
        "kcminputrc"."Mouse"."X11LibInputXAccelProfileFlat" = true;
        "kded5rc"."Module-browserintegrationreminder"."autoload" = false;
        "kded5rc"."Module-device_automounter"."autoload" = false;
        "kdeglobals"."DirSelect Dialog"."DirSelectDialog Size" = "922,587";
        "kdeglobals"."General"."TerminalApplication" = "kitty";
        "kdeglobals"."General"."TerminalService" = "kitty.desktop";
        "kdeglobals"."KFileDialog Settings"."Allow Expansion" = false;
        "kdeglobals"."KFileDialog Settings"."Automatically select filename extension" = true;
        "kdeglobals"."KFileDialog Settings"."Breadcrumb Navigation" = true;
        "kdeglobals"."KFileDialog Settings"."Decoration position" = 2;
        "kdeglobals"."KFileDialog Settings"."LocationCombo Completionmode" = 5;
        "kdeglobals"."KFileDialog Settings"."PathCombo Completionmode" = 5;
        "kdeglobals"."KFileDialog Settings"."Show Bookmarks" = false;
        "kdeglobals"."KFileDialog Settings"."Show Full Path" = false;
        "kdeglobals"."KFileDialog Settings"."Show Inline Previews" = true;
        "kdeglobals"."KFileDialog Settings"."Show Preview" = false;
        "kdeglobals"."KFileDialog Settings"."Show Speedbar" = true;
        "kdeglobals"."KFileDialog Settings"."Show hidden files" = true;
        "kdeglobals"."KFileDialog Settings"."Sort by" = "Name";
        "kdeglobals"."KFileDialog Settings"."Sort directories first" = true;
        "kdeglobals"."KFileDialog Settings"."Sort hidden files last" = false;
        "kdeglobals"."KFileDialog Settings"."Sort reversed" = false;
        "kdeglobals"."KFileDialog Settings"."Speedbar Width" = 192;
        "kdeglobals"."KFileDialog Settings"."View Style" = "DetailTree";
        "kdeglobals"."KScreen"."ScaleFactor" = 2;
        "kdeglobals"."KScreen"."ScreenScaleFactors" = "eDP-1=2;DP-1=2;HDMI-1=2;DP-2=2;HDMI-2=2;";
        "kdeglobals"."WM"."activeBackground" = "7,60,100";
        "kdeglobals"."WM"."activeBlend" = "53,153,205";
        "kdeglobals"."WM"."activeForeground" = "194,232,253";
        "kdeglobals"."WM"."inactiveBackground" = "7,60,100";
        "kdeglobals"."WM"."inactiveBlend" = "88,167,208";
        "kdeglobals"."WM"."inactiveForeground" = "194,232,253";
        "kscreenlockerrc"."Greeter/Wallpaper/org.kde.image/General"."Image" = "/home/jankoh/Downloads/house-mountains-snow-lake-beautiful-landscape-1186354-wallhere.com.jpg";
        "kscreenlockerrc"."Greeter/Wallpaper/org.kde.image/General"."PreviewImage" = "/home/jankoh/Downloads/house-mountains-snow-lake-beautiful-landscape-1186354-wallhere.com.jpg";
        "ksmserverrc"."General"."loginMode" = "emptySession";
        "kwalletrc"."Wallet"."First Use" = false;
        "kwinrc"."Desktops"."Id_1" = "0ae69f1a-8f97-4cf3-879b-5d74064f70e0";
        "kwinrc"."Desktops"."Number" = 1;
        "kwinrc"."Desktops"."Rows" = 1;
        "kwinrc"."Tiling"."padding" = 4;
        "kwinrc"."Tiling/abd18095-e6da-5b19-a690-179355dc8b16"."tiles" = "{\"layoutDirection\":\"horizontal\",\"tiles\":[{\"width\":0.25},{\"width\":0.5},{\"width\":0.25}]}";
        "kwinrc"."Tiling/d7ce7540-205d-51b2-b3a5-25a32ffd440a"."tiles" = "{\"layoutDirection\":\"horizontal\",\"tiles\":[{\"width\":0.25},{\"width\":0.5},{\"width\":0.25}]}";
        "kwinrc"."Tiling/e5ae5f20-2c3a-5283-8766-6d6c5b928523"."tiles" = "{\"layoutDirection\":\"horizontal\",\"tiles\":[{\"width\":0.25},{\"width\":0.5},{\"width\":0.25}]}";
        "kwinrc"."Xwayland"."Scale" = 1.5;
        "kwinrulesrc"."0df59ac6-f762-49e6-8bdc-204c70fc6ac6"."Description" = "Programm-Einstellungen für com.mitchellh.ghostty";
        "kwinrulesrc"."0df59ac6-f762-49e6-8bdc-204c70fc6ac6"."maximizehoriz" = true;
        "kwinrulesrc"."0df59ac6-f762-49e6-8bdc-204c70fc6ac6"."maximizehorizrule" = 3;
        "kwinrulesrc"."0df59ac6-f762-49e6-8bdc-204c70fc6ac6"."maximizevert" = true;
        "kwinrulesrc"."0df59ac6-f762-49e6-8bdc-204c70fc6ac6"."maximizevertrule" = 3;
        "kwinrulesrc"."0df59ac6-f762-49e6-8bdc-204c70fc6ac6"."wmclass" = "ghostty com.mitchellh.ghostty";
        "kwinrulesrc"."0df59ac6-f762-49e6-8bdc-204c70fc6ac6"."wmclasscomplete" = true;
        "kwinrulesrc"."0df59ac6-f762-49e6-8bdc-204c70fc6ac6"."wmclassmatch" = 1;
        "kwinrulesrc"."9fa54e82-47f4-45d2-b33d-6c4a53b4fe8c"."Description" = "Programm-Einstellungen für com.mitchellh.ghostty";
        "kwinrulesrc"."9fa54e82-47f4-45d2-b33d-6c4a53b4fe8c"."maximizehoriz" = true;
        "kwinrulesrc"."9fa54e82-47f4-45d2-b33d-6c4a53b4fe8c"."maximizehorizrule" = 3;
        "kwinrulesrc"."9fa54e82-47f4-45d2-b33d-6c4a53b4fe8c"."maximizevert" = true;
        "kwinrulesrc"."9fa54e82-47f4-45d2-b33d-6c4a53b4fe8c"."maximizevertrule" = 3;
        "kwinrulesrc"."9fa54e82-47f4-45d2-b33d-6c4a53b4fe8c"."maxsize" = "1463,870";
        "kwinrulesrc"."9fa54e82-47f4-45d2-b33d-6c4a53b4fe8c"."maxsizerule" = 2;
        "kwinrulesrc"."9fa54e82-47f4-45d2-b33d-6c4a53b4fe8c"."wmclass" = "ghostty com.mitchellh.ghostty";
        "kwinrulesrc"."9fa54e82-47f4-45d2-b33d-6c4a53b4fe8c"."wmclasscomplete" = true;
        "kwinrulesrc"."9fa54e82-47f4-45d2-b33d-6c4a53b4fe8c"."wmclassmatch" = 2;
        "kwinrulesrc"."General"."count" = 3;
        "kwinrulesrc"."General"."rules" = "0df59ac6-f762-49e6-8bdc-204c70fc6ac6,9fa54e82-47f4-45d2-b33d-6c4a53b4fe8c,b5305b69-af50-4011-b1c0-145e4ad74a70";
        "kwinrulesrc"."b5305b69-af50-4011-b1c0-145e4ad74a70"."Description" = "Programm-Einstellungen für kitty";
        "kwinrulesrc"."b5305b69-af50-4011-b1c0-145e4ad74a70"."maximizehorizrule" = 3;
        "kwinrulesrc"."b5305b69-af50-4011-b1c0-145e4ad74a70"."maximizevertrule" = 3;
        "kwinrulesrc"."b5305b69-af50-4011-b1c0-145e4ad74a70"."wmclass" = "kitty";
        "kwinrulesrc"."b5305b69-af50-4011-b1c0-145e4ad74a70"."wmclassmatch" = 1;
        "plasma-localerc"."Formats"."LANG" = "de_DE.UTF-8";
        "plasmarc"."Wallpapers"."usersWallpapers" = "/home/jankoh/.dotfiles/nixcold.png,/home/jankoh/Downloads/house-mountains-snow-lake-beautiful-landscape-1186354-wallhere.com.jpg";
        "spectaclerc"."GuiConfig"."captureDelay" = 5;
        "spectaclerc"."GuiConfig"."captureMode" = 0;
        "spectaclerc"."ImageSave"."lastImageSaveAsLocation" = "file:///run/media/jankoh/6745-2301/Janko Schule/sturmflut/hintergrund3.png";
        "spectaclerc"."ImageSave"."lastImageSaveLocation" = "file:///home/jankoh/Bilder/Bildschirmfotos/Bildschirmfoto_20250114_160744.png";
        "spectaclerc"."ImageSave"."translatedScreenshotsFolder" = "Bildschirmfotos";
        "spectaclerc"."VideoSave"."translatedScreencastsFolder" = "Bildschirmaufnahmen";
      };
      dataFile = {
        "kate/anonymous.katesession"."Document 0"."URL" = "file:///home/jankoh/.dotfiles/home.nix";
        "kate/anonymous.katesession"."Kate Plugins"."cmaketoolsplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."compilerexplorer" = false;
        "kate/anonymous.katesession"."Kate Plugins"."eslintplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."externaltoolsplugin" = true;
        "kate/anonymous.katesession"."Kate Plugins"."formatplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."katebacktracebrowserplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."katebuildplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."katecloseexceptplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."katecolorpickerplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."katectagsplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."katefilebrowserplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."katefiletreeplugin" = true;
        "kate/anonymous.katesession"."Kate Plugins"."kategdbplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."kategitblameplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."katekonsoleplugin" = true;
        "kate/anonymous.katesession"."Kate Plugins"."kateprojectplugin" = true;
        "kate/anonymous.katesession"."Kate Plugins"."katereplicodeplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."katesearchplugin" = true;
        "kate/anonymous.katesession"."Kate Plugins"."katesnippetsplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."katesqlplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."katesymbolviewerplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."katexmlcheckplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."katexmltoolsplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."keyboardmacrosplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."ktexteditorpreviewplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."latexcompletionplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."lspclientplugin" = true;
        "kate/anonymous.katesession"."Kate Plugins"."openlinkplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."rainbowparens" = false;
        "kate/anonymous.katesession"."Kate Plugins"."rbqlplugin" = false;
        "kate/anonymous.katesession"."Kate Plugins"."tabswitcherplugin" = true;
        "kate/anonymous.katesession"."Kate Plugins"."textfilterplugin" = true;
        "kate/anonymous.katesession"."MainWindow0"."Active ViewSpace" = 0;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-H-Splitter" = "0,1235,0";
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-0-Bar-0-TvList" = "kate_private_plugin_katefiletreeplugin,kateproject,kateprojectgit,lspclient_symbol_outline";
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-0-LastSize" = 200;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-0-SectSizes" = 0;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-0-Splitter" = 620;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-1-Bar-0-TvList" = "";
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-1-LastSize" = 200;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-1-SectSizes" = 0;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-1-Splitter" = 547;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-2-Bar-0-TvList" = "";
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-2-LastSize" = 200;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-2-SectSizes" = 0;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-2-Splitter" = 577;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-3-Bar-0-TvList" = "output,diagnostics,kate_plugin_katesearch,kateprojectinfo,kate_private_plugin_katekonsoleplugin";
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-3-LastSize" = 200;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-3-SectSizes" = 0;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-3-Splitter" = 732;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-Style" = 2;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-Sidebar-Visible" = true;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-diagnostics-Position" = 3;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-diagnostics-Show-Button-In-Sidebar" = true;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-diagnostics-Visible" = false;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kate_plugin_katesearch-Position" = 3;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kate_plugin_katesearch-Show-Button-In-Sidebar" = true;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kate_plugin_katesearch-Visible" = false;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kate_private_plugin_katefiletreeplugin-Position" = 0;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kate_private_plugin_katefiletreeplugin-Show-Button-In-Sidebar" = true;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kate_private_plugin_katefiletreeplugin-Visible" = false;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kate_private_plugin_katekonsoleplugin-Position" = 3;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kate_private_plugin_katekonsoleplugin-Show-Button-In-Sidebar" = true;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kate_private_plugin_katekonsoleplugin-Visible" = false;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kateproject-Position" = 0;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kateproject-Show-Button-In-Sidebar" = true;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kateproject-Visible" = false;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kateprojectgit-Position" = 0;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kateprojectgit-Show-Button-In-Sidebar" = true;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kateprojectgit-Visible" = false;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kateprojectinfo-Position" = 3;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kateprojectinfo-Show-Button-In-Sidebar" = true;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-kateprojectinfo-Visible" = false;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-lspclient_symbol_outline-Position" = 0;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-lspclient_symbol_outline-Show-Button-In-Sidebar" = true;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-lspclient_symbol_outline-Visible" = false;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-output-Position" = 3;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-output-Show-Button-In-Sidebar" = true;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-ToolView-output-Visible" = false;
        "kate/anonymous.katesession"."MainWindow0"."Kate-MDI-V-Splitter" = "0,620,0";
        "kate/anonymous.katesession"."MainWindow0"."ToolBarsMovable" = "Disabled";
        "kate/anonymous.katesession"."MainWindow0 Settings"."ToolBarsMovable" = "Disabled";
        "kate/anonymous.katesession"."MainWindow0 Settings"."WindowState" = 10;
        "kate/anonymous.katesession"."MainWindow0-Splitter 0"."Children" = "MainWindow0-ViewSpace 0";
        "kate/anonymous.katesession"."MainWindow0-Splitter 0"."Orientation" = 1;
        "kate/anonymous.katesession"."MainWindow0-Splitter 0"."Sizes" = 1235;
        "kate/anonymous.katesession"."MainWindow0-ViewSpace 0"."Active View" = 0;
        "kate/anonymous.katesession"."MainWindow0-ViewSpace 0"."Count" = 1;
        "kate/anonymous.katesession"."MainWindow0-ViewSpace 0"."Documents" = 0;
        "kate/anonymous.katesession"."MainWindow0-ViewSpace 0"."View 0" = 0;
        "kate/anonymous.katesession"."MainWindow0-ViewSpace 0 0"."CursorColumn" = 15;
        "kate/anonymous.katesession"."MainWindow0-ViewSpace 0 0"."CursorLine" = 38;
        "kate/anonymous.katesession"."MainWindow0-ViewSpace 0 0"."ScrollLine" = 12;
        "kate/anonymous.katesession"."Open Documents"."Count" = 1;
        "kate/anonymous.katesession"."Open MainWindows"."Count" = 1;
        "kate/anonymous.katesession"."Plugin:kateprojectplugin:"."projects" = "";
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."BinaryFiles" = false;
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."CurrentExcludeFilter" = "-1";
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."CurrentFilter" = "-1";
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."ExcludeFilters" = "";
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."ExpandSearchResults" = false;
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."Filters" = "";
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."FollowSymLink" = false;
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."HiddenFiles" = false;
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."MatchCase" = false;
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."Place" = 1;
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."Recursive" = true;
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."Replaces" = "";
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."Search" = "";
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."SearchAsYouTypeAllProjects" = true;
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."SearchAsYouTypeCurrentFile" = true;
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."SearchAsYouTypeFolder" = true;
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."SearchAsYouTypeOpenFiles" = true;
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."SearchAsYouTypeProject" = true;
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."SearchDiskFiles" = "";
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."SearchDiskFiless" = "";
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."SizeLimit" = 128;
        "kate/anonymous.katesession"."Plugin:katesearchplugin:MainWindow:0"."UseRegExp" = false;
      };
    };

    # The state version is required and should stay at the version you originally installed.
    home.stateVersion = "24.11";
}

